# Generated by Django 4.2.7 on 2023-12-06 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gostinitsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заезда')),
                ('duration', models.IntegerField(default=1, verbose_name='Продолжительность пребывания в днях')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Одобрена'), (0, 'Отклонена'), (2, 'Ожидает одобрения')], default=2, verbose_name='Статус')),
                ('operator_decision', models.BooleanField(blank=True, null=True, verbose_name='Решение туроператора')),
            ],
            options={
                'verbose_name': 'Бронирование комнаты',
                'verbose_name_plural': 'Бронирование комнат',
                'ordering': ['check_in_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, verbose_name='Номер комнаты')),
                ('is_status', models.IntegerField(choices=[(1, 'Свободен'), (0, 'Занят'), (2, 'В заявке на бронирование')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['hotel', 'room_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='gostinitsa',
            options={'ordering': ['-time_create'], 'verbose_name': 'Гостиницы', 'verbose_name_plural': 'Гостиницы'},
        ),
        migrations.AddField(
            model_name='gostinitsa',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%M/%D', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='gostinitsa',
            index=models.Index(fields=['-time_create'], name='gostinitsa__time_cr_50b219_idx'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostinitsa.gostinitsa', verbose_name='Принадлежит гостинице'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gostinitsa.room', verbose_name='Комната для бронирования'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='gostinitsa__room_nu_0afb15_idx'),
        ),
    ]
