# Generated by Django 4.2.7 on 2023-11-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gostinitsa',
            name='slug',
        ),
    ]
