# Generated by Django 4.2.7 on 2023-12-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0002_item_reservation_room_alter_gostinitsa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number', 'hotel'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.RenameField(
            model_name='gostinitsa',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер комнаты'),
        ),
    ]
