# Generated by Django 4.2.7 on 2023-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0003_gostinitsa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gostinitsa',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
