# Generated by Django 4.2.7 on 2023-12-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0003_alter_room_options_rename_image_gostinitsa_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gostinitsa',
            options={'ordering': ['time_create'], 'verbose_name': 'Гостиницы', 'verbose_name_plural': 'Гостиницы'},
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True, verbose_name='Номер комнаты'),
        ),
    ]
