# Generated by Django 4.2.7 on 2023-11-12 16:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0004_alter_gostinitsa_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gostinitsa',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='gostinitsa',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
