# Generated by Django 4.2.7 on 2023-11-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0005_alter_gostinitsa_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('open', models.BooleanField(choices=[(0, 'Занят'), (1, 'Свободен')], default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostinitsa.gostinitsa')),
            ],
        ),
    ]
