# Generated by Django 4.2.7 on 2023-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0005_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(verbose_name='Номер комнаты'),
        ),
    ]
