# Generated by Django 4.2.7 on 2023-11-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0006_room'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gostinitsa',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='open',
            new_name='status',
        ),
    ]
