# Generated by Django 4.2.7 on 2023-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinitsa', '0007_alter_gostinitsa_managers_rename_open_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(0, 'Занят'), (1, 'Свободен')], default=0),
        ),
    ]
